### ISSUE TITLE
wither proof bricks not wither proof :-D

### ISSUE THREAD

**Issue by shabitai** [MrComputerGhost/Runic-Dungeons#12]
hey there, 

first of all: thanks to all mod devs! You keep Minecraft interessting and enjoyable :-)

Playing the latest version of FTB infinity (05/06/2015)
here my issues:
1. Build a witherfarm out of witherproof -bricks and -glas from your mod. They will be destroyed from the explosion. Not all at once but every time a few. Don't have any pictures, but I used Enhanced Teleposition focus and Teleposers from blood Magic to transfer the blocks, in case that is the issue.
2.) I keep getting a weired duping glitch. Even there are only a few runic dungen bricks left on the outer side of the witherfarm (I replaced the destroyed blocks with EnderIO's witherproof blocks) I keep getting bricks on every Wither explosion. It is 100% a duping glitch, 'couse I have over 100 Witherproof bricks in my system now, building only a few...

other than that I want to mention that:

a) the compressed obsidian recepie is a cool idea, but makes the blocks ridicilous expensive in my opinion. Surely it's ment to be expensive, but compared with EnderIO I would not choose your Blocks a second time (even without the bug of course)
b) I think they should be harvestable, since you really can't replace them if only one block is on the wrong position, making building with them extremly unfunny. (That's why i used Teleposers in the first place.)

Lastly, personally I think the runic dungeons portal should also be harvestable or you should be able to backcraft the portal with the chalk thing, for the same reason, if you don't like the portal on it's spot anymore you really are screwed up.

Other than that, I enjoy your mod a lot and thanks again. hope I was able to help.

**Comment by MrComputerGhost** [comment]
I will try to make sure and fix that. It is meant to be expensive. The EnderIO ones do require a tiny bit less, but those require alloys. The portal is harvestable, break the edge of the runic circle. Make sure you are using the latest version, then report back to be please.

**Comment by MrComputerGhost** [comment]
Should be fixed as of v1.1.5
