### ISSUE TITLE
All amulets are removed from game with latest update

### ISSUE THREAD

**Issue by Staegrin** [MrComputerGhost/Runic-Dungeons#14]
Just updated to version 1.1.4 and all amulets have been removed from the game. They're still in the config and are set to be allowed =true.

Not sure if this is intentional?

**Comment by MrComputerGhost** [comment]
This is intentional, as the amulets are being rebalanced. You are looking at the wrong config, the config has been moved and reset to RunicDungeons\RunicDungeons.cfg
