### ISSUE TITLE
Ender Belt not disabling properly

### ISSUE THREAD

**Issue by BlackAce21** [MrComputerGhost/Runic-Dungeons#15]
Running: Infinity mod pack version 1.5.1
Runic Dungeons version: 1.1.3
FastCraft: Disabled server side
Cauldron: Yes

Simply put the ender belt isn't properly removing its information from a player when it is removed. The player still has an entry in their player.dat file stating "EnderBeltIsOn: 1" and I had to manually remove it from the player's .dat file to stop it from teleporting him around every time he takes damage. Not a super critical error but an annoying one. Idk if this is fixed yet because I couldn't find a changelog and I don't have much time at the moment but I thought you should know of the issue if it hasn't been fixed. Great mod, great fun, good luck, and good day ^_^

**Comment by MrComputerGhost** [comment]
Remove Completely as of v1.1.5
