### ISSUE TITLE
Getting Entity ID conflicts from ClientProxy.class line:10 and CommonProxy.class line:11

### ISSUE THREAD

**Issue by chinupt** [MrComputerGhost/Runic-Dungeons#17]
I'm no code junkie, I just looked over the crashlog and saw this error. After much research I determined it is beyond my control to fix entity id's because they are contained in the source code(and not available to edit in the config files.) If you are capable of making this fix, I would be grateful.

**Comment by MrComputerGhost** [comment]
Yeah, apparently I broke it in the last update, will be fixed in the next release.

**Comment by MrComputerGhost** [comment]
Should be fixed as of v1.1.5
