### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Claycorp** [MrComputerGhost/Runic-Dungeons#19]
http://pastebin.com/5kzTYcBD

Happens to all blocks that cause damage to the player when you collide with a block.

**Comment by lordYARO** [comment]
http://pastebin.com/qWns67gM

Crashes the server when stepping on maze hedge in Twilight forest. All other blocks that cause damage to the player when you collide with a block kick you for previous error.

**Comment by MrComputerGhost** [comment]
I've been away for two weeks, so sorry about this. I'll get out yet another bugfix release either today or tomorrow. Thank you.
