### ISSUE TITLE
Wither Boss-Proof Blocks Drop 2 Blocks on Destroy 

### ISSUE THREAD

**Issue by KMGuinther** [MrComputerGhost/Runic-Dungeons#21]
When I destroy a Wither Boss-Proof block in creative 1 real block drops and 1 fake block drops (fake meaning that the item is on the floor but you can't pick it up). This happens if I am in creative or in survival using a pick. This happened when I had other mods installed but I then removed all the mods and left only Runic Dungeons in and it still happened. I was using Forge 10.13.4.1448 and Runic Dungeons 1.1.5c.

**Comment by MrComputerGhost** [comment]
Will be fixed in the next update

**Comment by oxyum** [comment]
Also Runic Glass converts to Dungeon Bricks on destroing with pickaxe or when Wither exploding near that blocks.

**Comment by MrComputerGhost** [comment]
Fixed as of 1.1.6a
