### ISSUE TITLE
Portal will not generate

### ISSUE THREAD

**Issue by hulpet** [MrComputerGhost/Runic-Dungeons#22]
The mod looks awesome from what I've seen via Youtube.  My problem is that I cannot generate the portal.  Just created the magical staff after finding 3 chalk.  Created the chiseled stone brick and attempted to create the portal, it does nothing.  I've tried the 4 chiseled stone and 9 chiseled stone arrangement.  I've tried above the surface and level with the ground.  I've tried creating it in another mystcraft age and on other types of surfaces.

I'm using a multiplayer server of Feed the Beast Infinity v1.10.1.  I've recently upgraded it from 1.7.0.  When starting the upgraded server I did receive a warning that one of the Runic amulets (Cactus, I think) did not exist so had to skip it using the /FML confirm command or something like that.  I did not attempt to create the portal prior to the upgrade.  

Do you have any suggestions or troubleshooting advice?  Thanks...

**Comment by MrComputerGhost** [comment]
Can you send me a screenshot of your setup?

**Comment by hulpet** [comment]
Sorry to waste your time.  Just tried it again to send a screenshot and it worked perfectly, no issues.  Probably had something setup wrong the first time.  Love the mod, nice job!
