### ISSUE TITLE
'WitherProof' blocks are in fact, not witherproof.

### ISSUE THREAD

**Issue by rikai** [MrComputerGhost/Runic-Dungeons#24]
Version: 1.1.5c

This one is easy to reproduce.

Create a wither cage out of 'WitherBoss-Proof' runic glass, spawn a wither in it. It will quickly destroy blocks and escape.

First the runic glass blocks will be come WitherBoss-Proof dungeon brick on the first hit, second hit will destroy the WitherBoss-Proof dungeon brick. Extremely disappointing to have learned this on a survival world... was quite an expensive lesson.

**Comment by MrNoe93** [comment]
I also had this experience last night. Just thankful it wasn't in hardcore :)

**Comment by MrComputerGhost** [comment]
Fixed as of 1.1.6a
