### ISSUE TITLE
Pendants not working correctly.

### ISSUE THREAD

**Issue by Aulton** [MrComputerGhost/Runic-Dungeons#3]
For one, your night vision pendant is going to give someone a seizure if they look out into the distance with it equipped. The sky flashes so quickly it gave me a headache in a few moments. The duration is set too short and vanilla mechanics with night vision take over, flashing the horizon. Do like Blood Magic and set the duration to 20 seconds, so you avoid the flashing horizon.

Secondly, the health regen one doesn't actually regenerate any health. I'm assuming the duration runs out before it has a chance to tick, considering you have it set to 0.

Thirdly, these are the only two I've tested so far, but based on the duration of these two, I'm assuming that they're all set to this amount. I'd provide screenshots, but these two are not really screenshot friendly, and videos are an impossibility for me. I hope these explanations are enough though.

**Comment by MrComputerGhost** [comment]
Fixed as of 1.0.6 and 1.0.6b
