### ISSUE TITLE
Block Dupe bug

### ISSUE THREAD

**Issue by Gunner76th** [MrComputerGhost/Runic-Dungeons#30]
The Runic Glass (Wither-boss Proof) will duplicate if an explosion happens that would normally break glass. This includes withers, TNT, creepers, or any other form of explosion. The glass stays in place, and new glass spawns as dropped items on the ground. 

Conditions to recreate: 
While playing the FTP Infinity pack set to expert mode, create a room made out of Runic Glass (wither-boss proof)
Spawn a wither using soul sand and 3 wither skulls, or place TNT inside the room and ignite
When wither forms and does its explosion, or the TNT detonates, there will be new glass items on the ground, even though no glass has broken. 

Also, the glass does not contain explosions like the Wither Proof blocks from other mobs do, thus allowing the player and environment to be damaged by explosions that occur within a room made of Runic Glass (Wither-boss proof).

**Comment by Gunner76th** [comment]
It should be noted that the Infinity pack is running the 1.1.6a release.

**Comment by Paktosan** [comment]
Our server is also affected. Is there a fix for it available?

**Comment by Paktosan** [comment]
I fixed the glass in my own version of Runic Dungeons.
[runic.zip](https://github.com/MrComputerGhost/Runic-Dungeons/files/298478/runic.zip)
Is everything working as expected with that version? It can be used as easy drop in replacement and is compatible with the version containing the bug.

**Comment by MrComputerGhost** [comment]
It was fixed as of the latest release. Note the latest release is 1.1.6d.

**Comment by ExDomino** [comment]
We are on 1.1.7b and we still have this issue.
