### ISSUE TITLE
InstantiationException error

### ISSUE THREAD

**Issue by gixmy** [MrComputerGhost/Runic-Dungeons#32]
I'm getting an InstantiationException on server startup using forge 1558:

[fml-server-latest.log.txt](https://github.com/MrComputerGhost/Runic-Dungeons/files/108113/fml-server-latest.log.txt)

This is with the following mods installed:

Baubles-1.7.10-1.0.1.10.jar  
runicdungeons-1.1.6a.jar

**Comment by MrComputerGhost** [comment]
Fixed in the next release. Thank you.
