### ISSUE TITLE
New Instance Issue?(Not a Clue...)

### ISSUE THREAD

**Issue by O13SC3N3** [MrComputerGhost/Runic-Dungeons#33]
FastCraft enabled.
Forge 1566 (and with 1558)

http://pastebin.com/s4gamZWU

**Comment by O13SC3N3** [comment]
This mod dead?

**Comment by Bennyboy1695** [comment]
Whats mods were in this instance as that pastebin doesnt say anything about which mod was causing the issue. A copy of the fml-client-latest will help to diagnose the issue

**Comment by O13SC3N3** [comment]
Runic Dungeons by itself

**Comment by O13SC3N3** [comment]
Issue seems to be the same stand alone and with current modpack. same issue exist with FTB Infinity as well.

Minecraft 1.7.10
RunicDungeons 1.16b
Forge 1614

Error: http://pastebin.com/raw/ymCSdQ6D
Console Log: http://pastebin.com/raw/yBmJeeS4

**Comment by MrComputerGhost** [comment]
Fixed in the next release. Thank you.
