### ISSUE TITLE
Belt of Flight de-activates when changing dimension or when relogging into a server

### ISSUE THREAD

**Issue by rob5300** [MrComputerGhost/Runic-Dungeons#34]
The **Belt of Flight** stops working when changing dimensions and when leaving and re entering a server. This apears to have been a bug in the past.

This happens in the current version of FTB Infinity (2.3.5) which has the latest version of Runic Dungeons (v1.1.6a).

Hope you can resolve this issue once again

**Comment by MrComputerGhost** [comment]
Fixed as of next release. Thank you.
