### ISSUE TITLE
Server crash..Runic Dungeons v1.0.3

### ISSUE THREAD

**Issue by Fadirstave** [MrComputerGhost/Runic-Dungeons#4]
If I'm reading this correct...The crash reports reads that its trying to pass an event onto something that doesn't exist. Very strange. Any ideas on a hot fix I could do?

http://pastebin.com/7Da22p1C

**Comment by MrComputerGhost** [comment]
What was going on when you got this crash?

**Comment by Fadirstave** [comment]
If my memory serves me correct. I do believe someone had either gone to the DIM or was exploring it.

**Comment by MrComputerGhost** [comment]
I need more information.

**Comment by Itszuvalex** [comment]
The crash is because it's referencing a client-side only class from the server.

**Comment by Sir-Will** [comment]
I got the crash too. It happens if someone removes the chalk/mysterious runes

**Comment by MrComputerGhost** [comment]
If it crashes because 'someone removes the chalk/mysterious runes', then you need to update the version of Runic Dungeons. That has been fixed for a long while.

**Comment by Sir-Will** [comment]
I'm useing the version 1.0.6B which is currenlty in the infinity modpack.

In which version got it fixed and in which class?

**Comment by MrComputerGhost** [comment]
Current version of Infinity is 1.3.1, and uses RD 1.1.0, where I know for a fact that that is fixed. Version it was fixed in was 1.0.8

**Comment by Sir-Will** [comment]
Okay. I'm on the recommended version, I will wait for the recommended version push then.
