### ISSUE TITLE
Failed integration with other mods

### ISSUE THREAD

**Issue by wierzejs** [MrComputerGhost/Runic-Dungeons#42]
Hi,
I have a problem, I'm running Runic mods on ftb infinity evolved on expert mode and when I entered the dimension I've noticed that everything in the chests was from vanilla minecraft, no other mods included in modpack whatsoever apart from a mod dense ores. I've found one room where there were random ores growing from the ground and one of them was from dense ores.
Despite looking around if quite few rooms I haven't found anything more.

P.S. I wanted to try to restart the dimension and try to generate it again hoping it might help, I'm running it on a server and I wanted to ask in which folder I can find the files for runic dungeons chunks

**Comment by MrComputerGhost** [comment]
This is due to the configs set by the FTB Team. They disabled most of the modded loot.
