### ISSUE TITLE
Spawning Dungeon Guardian per Spawn Egg crashed my FTB Infinity Server

### ISSUE THREAD

**Issue by tekytek** [MrComputerGhost/Runic-Dungeons#6]
Title says it. It would crash even after restart. Needed to kill him in Singleplayer to get it working again. Modpack is running with the runicdongeons-1.0.2.jar.

If you need any logs or anything just ask me please, this is my first report. :)

Teky

**Comment by MrComputerGhost** [comment]
Crash log?

**Comment by tekytek** [comment]
I got 3 of them because i restarted 2 times.
1: http://pastebin.com/WsCDDnLc
2: http://pastebin.com/RsCX4x3U
3: http://pastebin.com/wUXszkA3

**Comment by MrComputerGhost** [comment]
Bug was fixed as of version 1.0.3

Latest version as of now is 1.0.8b
