### ISSUE TITLE
exitcode 255

### ISSUE THREAD

**Issue by MeM0402** [MrComputerGhost/Runic-Dungeons#7]
I'm not sure if this is on the mod side or MultiMC, but I thought I would start here. I'm putting together a personal modpack and was watching iJevin play around with this mod and wanted to try it. I added it to MultiMC, but when I try to load up the game, it exits with exitcode 255

http://paste.ee/p/2t4in

If this is a problem with MultiMC, I'm sorry for wasting your time.

**Comment by MrComputerGhost** [comment]
Trying to reproduce the bug. I'll see what happens.

**Comment by MeM0402** [comment]
Okay, thank you :)
