### ISSUE TITLE
Obsidian infused dungeon bricks unbreakable?

### ISSUE THREAD

**Issue by 252rer** [MrComputerGhost/Runic-Dungeons#8]
I made some dungeon bricks (obsidian infused) for my house and can't figure out how to break them. Walia says unbreakable with pickaxes. They are not the unbreakable class in nei. The crafted glass has been working fine. Runic dungeons 1.1.1
ps. Also do crafted runic lamps require silk touch to recover?

**Comment by MrComputerGhost** [comment]
Those bugs have been fixed as of 1.1.2b
