### ISSUE TITLE
Flat bedrock messing with the RD dimension.

### ISSUE THREAD

**Issue by Aulton** [MrComputerGhost/Runic-Dungeons#9]
http://puu.sh/hrZOu/67c05937a0.png

Exactly as the title states. There is no way to move ahead, nor a way to go back if you enable CoFH's flat bedrock. Not sure if there's something you can do to disable that option from affecting your dimension.

**Comment by MrComputerGhost** [comment]
Will be fixed in 1.1.3, thank you.

**Comment by MrComputerGhost** [comment]
Fixed as of 1.1.3
